http:
  services:
    skipify-dev-back:
      loadBalancer:
        servers:
          - url: "http://localhost:8000"
    
    skipify-dev-front:
      loadBalancer:
        servers:
          - url: "http://localhost:5173"

  routers:
    to-skipify-dev-back-staff:
      entryPoints:
        - "websecure"
      tls: {}
      rule: "Host(`skipify.local`) && PathPrefix(`/staff`)"
      service: skipify-dev-back
      priority: 110

    to-skipify-dev-back-api:
      entryPoints:
        - "websecure"
      tls: {}
      rule: "Host(`skipify.local`) && PathPrefix(`/api`)"
      service: skipify-dev-back
      priority: 108

    to-skipify-dev-back-api-wildcard:
      entryPoints:
        - "websecure"
      tls: {}
      rule: "Host(`skipify.local`) && PathPrefix(`/api/`)"
      service: skipify-dev-back
      priority: 107

    to-skipify-dev-back-static-admin:
      entryPoints:
        - "websecure"
      tls: {}
      rule: "Host(`skipify.local`) && PathPrefix(`/static/admin`)"
      service: skipify-dev-back
      priority: 106

    to-skipify-dev-back-static-rest-framework:
      entryPoints:
        - "websecure"
      tls: {}
      rule: "Host(`skipify.local`) && PathPrefix(`/static/rest_framework/`)"
      service: skipify-dev-back
      priority: 105

    to-skipify-dev-front:
      entryPoints:
        - "websecure"
      rule: "Host(`skipify.local`) && PathPrefix(`/`)"
      tls: {}
      service: skipify-dev-front
      priority: 50
